---
name: Class-Dot
version: 1.0.3
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Simple way of creating accessor methods.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  version: 0
build_requires:
  Test::Simple: 0.42
recommends:
  IO::Capture::Stderr: 0
  Test::Exception: 0.25
dynamic_config: 0
provides:
  Class::Dot:
    file: lib/Class/Dot.pm
    version: 1.0.3
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Module
