---
name: Class-Dot
version: 2.0.0_01
author:
  - 'Ask Solem <ASKSH@cpan.org>'
abstract: Simple and fast properties for Perl 5.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  version: 0
build_requires:
  Test::Simple: 0.42
recommends:
  IO::Capture::Stderr: 0
  Test::Exception: 0.25
dynamic_config: 0
provides:
  Class::Dot:
    file: lib/Class/Dot.pm
    version: 2.0.0_01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: Module
