--- 
abstract: Simple and fast properties for Perl 5.
author: 
  - Ask Solem <asksh@cpan.org>
build_requires: 
  Scalar::Util: 1.14
  Test::Simple: 0.42
distribution_type: module
generated_by: Module::Install version 0.68
license: bsd
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Class-Dot
no_index: 
  directory: 
    - examples
    - devel
    - inc
    - t
recommends: 
  IO::Capture: 0
  Test::Exception: 0.25
requires: 
  perl: 5.6.0
  version: 0
version: 2.0.0_04
